apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
      - name: finance
        image: ghcr.io/abdulmalikagboola/my-react-app

        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: argocd

spec:
  selector:
    app: app
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: LoadBalancer
